#ifndef __PCM_STREAM_CONST_H
#define __PCM_STREAM_CONST_H

#define PCM_PLAYBACK_RATE            13300

#define PCM_STREAM_LEN_SAMPLES       512
#define PCM_STREAM_BUFFERLEN_SAMPLES 256

#define PCM_STREAM8_SIZE             PCM_STREAM_LEN_SAMPLES
#define PCM_STREAM8_BUFFER_SIZE      PCM_STREAM_BUFFERLEN_SAMPLES

#define PCM_STREAM16_SIZE            PCM_STREAM_LEN_SAMPLES * 2
#define PCM_STREAM16_BUFFER_SIZE     PCM_STREAM_BUFFERLEN_SAMPLES * 2

#endif